services:
  nifi:
    image: apache/nifi:2.1.0
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=admin12345678

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=nifi_lab
    volumes:
      - ./postgres-data:/var/lib/postgresql/data